# Generated by Django 2.1.4 on 2019-02-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(blank=True, null=True, verbose_name='学号')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='姓名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('Institute', models.CharField(blank=True, max_length=32, null=True, verbose_name='学院')),
                ('introduce', models.CharField(blank=True, max_length=255, null=True, verbose_name='个人介绍')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='邮箱')),
                ('latest_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最近登录时间')),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='avator', verbose_name='头像')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
    ]
