# Generated by Django 2.1.4 on 2019-01-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='introduce',
            field=models.CharField(max_length=255, verbose_name='个人介绍'),
        ),
    ]
